version: '3'
services:
  nginx:
    image: nginx:latest
    links:
            - php-fpm:php-fpm
    ports: 
      - "88:80"
    restart: always
    volumes:
       - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
       - "./nginx/conf.d:/etc/nginx/conf.d"
       - "./html:/usr/share/nginx/html"
    networks:
      - default
  php-fpm:
    build: ./php
    links:
     - redis:redis
    ports: 
     - 9000:9000
    volumes:
    - ./html/:/usr/share/nginx/html
    networks:
      - default
  redis:
      build: ./redis
      ports:
        - 6379:6379
      networks:
       - default

